### ISSUE TITLE
poetry show package throws error

### ISSUE THREAD

**Issue by stinovlas** [sdispater/poetry#1401]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 19.04 Disco Dingo
- **Poetry version**: `1.0.0b1`

## Issue
I added `django` as a dependency to my project. When I call `poetry show django -vvv`, I get following error:

```
Using virtualenv: /home/jmusilek/.envs/test

[TypeError]
render() missing 1 required positional argument: 'io'

Traceback (most recent call last):
  File "/home/jmusilek/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 132, in run
    status_code = command.handle(parsed_args, io)
  File "/home/jmusilek/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 119, in handle
    status_code = self._do_handle(args, io)
  File "/home/jmusilek/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 167, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/jmusilek/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/jmusilek/.poetry/lib/poetry/console/commands/show.py", line 89, in handle
    table.render()
```

The same command is working fine with `poetry@0.12.17`, I'm getting the error only in `poetry@1.0.0b1`.
