### PR TITLE
Handle missing license ('NoneType' object has no attribute 'lower')

### LINKED ISSUE #501: Missing `license` key explodes rather than logging a useful message
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14
- **Poetry version**: 0.12.0

## Issue

After updating to 0.12.0, almost all commands fail because my pyproject.toml doesn't have a license field.

Verbose output:

```
> poetry shell -vvv
                                              
[AttributeError]               
'NoneType' object has no attribute 'lower'  
                                              
Exception trace:
 /Users/seankelley/.poetry/lib/poetry/_vendor/py3.6/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /Users/seankelley/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /Users/seankelley/.poetry/lib/poetry/_vendor/py3.6/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /Users/seankelley/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /Users/seankelley/.poetry/lib/poetry/_vendor/py3.6/cleo/commands/base_command.py in run() at line 136
   self.initialize(input_, output_)
 /Users/seankelley/.poetry/lib/poetry/console/commands/env_command.py in initialize() at line 16
   o, self.poetry.package.name, cwd=self.poetry.file.parent
 /Users/seankelley/.poetry/lib/poetry/console/commands/command.py in poetry() at line 62
   return self.get_application().poetry
 /Users/seankelley/.poetry/lib/poetry/console/application.py in poetry() at line 60
   self._poetry = Poetry.create(os.getcwd())
 /Users/seankelley/.poetry/lib/poetry/poetry.py in create() at line 120
   license_ = license_by_id(local_config.get("license"))
 /Users/seankelley/.poetry/lib/poetry/spdx/__init__.py in license_by_id() at line 14
   id = identifier.lower()

shell
```

I would expect it to fail in the same way that it does for other missing keys:

```
[NonExistentKey]  
'Key "name" does not exist.'   
```

...or to not require a license field at all (why does it?).

### PR DESCRIPTION
**Pull request by jacebrowning**
After upgrading to `0.12.0`, I ran into the following exception:

```
poetry lock -v

[AttributeError]
'NoneType' object has no attribute 'lower'

Exception trace:
 /Users/Browning/.pyenv/versions/3.7.0/lib/python3.7/site-packages/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /Users/Browning/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /Users/Browning/.pyenv/versions/3.7.0/lib/python3.7/site-packages/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /Users/Browning/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /Users/Browning/.pyenv/versions/3.7.0/lib/python3.7/site-packages/cleo/commands/base_command.py in run() at line 136
   self.initialize(input_, output_)
 /Users/Browning/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/console/commands/env_command.py in initialize() at line 16
   o, self.poetry.package.name, cwd=self.poetry.file.parent
 /Users/Browning/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/console/commands/command.py in poetry() at line 62
   return self.get_application().poetry
 /Users/Browning/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/console/application.py in poetry() at line 60
   self._poetry = Poetry.create(os.getcwd())
 /Users/Browning/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/poetry.py in create() at line 120
   license_ = license_by_id(local_config.get("license"))
 /Users/Browning/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/spdx/__init__.py in license_by_id() at line 14
   id = identifier.lower()

lock
```

My understanding is that licenses are optional so we need to handle the case where the `pyproject.toml` does not contain a `license` key.

---

Fixes #501

### CODE REVIEW

**Comment by jacebrowning** [comment]
Please let me know if this check should happen higher up the chain.

**Comment by jacebrowning** [comment]
This was already fixed in https://github.com/sdispater/poetry/commit/bf112c2506aa90cea98ff523d71f9a0feec61367
