### ISSUE TITLE
`poetry lock` fails with `'NoneType' object has no attribute 'requires'`

### ISSUE THREAD

**Issue by rainyday** [sdispater/poetry#94]
After upgrading to 0.9 I am getting the following error when locking packages:

```
poetry lock -v
Using virtualenv: /Users/<User>/Library/Caches/pypoetry/virtualenvs/<project>-py2.7
Updating dependencies
Resolving dependencies..................................................................................................................................

[AttributeError]
'NoneType' object has no attribute 'requires'

Exception trace:
 /Users/<User>/.pyenv/versions/2.7.14/lib/python2.7/site-packages/poetry/_vendor/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /Users/<User>/.pyenv/versions/2.7.14/lib/python2.7/site-packages/poetry/console/application.py in do_run() at line 84
   return super(Application, self).do_run(i, o)
 /Users/<User>/.pyenv/versions/2.7.14/lib/python2.7/site-packages/poetry/_vendor/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /Users/<User>/.pyenv/versions/2.7.14/lib/python2.7/site-packages/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /Users/<User>/.pyenv/versions/2.7.14/lib/python2.7/site-packages/poetry/_vendor/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /Users/<User>/.pyenv/versions/2.7.14/lib/python2.7/site-packages/poetry/_vendor/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /Users/<User>/.pyenv/versions/2.7.14/lib/python2.7/site-packages/poetry/console/commands/lock.py in handle() at line 35
   return installer.run()
 /Users/<User>/.pyenv/versions/2.7.14/lib/python2.7/site-packages/poetry/installation/installer.py in run() at line 73
   self._do_install(local_repo)
 /Users/<User>/.pyenv/versions/2.7.14/lib/python2.7/site-packages/poetry/installation/installer.py in _do_install() at line 176
   ops = solver.solve(request, fixed=fixed)
 /Users/<User>/.pyenv/versions/2.7.14/lib/python2.7/site-packages/poetry/puzzle/solver.py in solve() at line 48
   vertex, requested
 /Users/<User>/.pyenv/versions/2.7.14/lib/python2.7/site-packages/poetry/puzzle/solver.py in _get_tags_for_vertex() at line 152
   edge.origin, requested
 /Users/<User>/.pyenv/versions/2.7.14/lib/python2.7/site-packages/poetry/puzzle/solver.py in _get_tags_for_vertex() at line 152
   edge.origin, requested
 /Users/<User>/.pyenv/versions/2.7.14/lib/python2.7/site-packages/poetry/puzzle/solver.py in _get_tags_for_vertex() at line 141
   for req in edge.origin.payload.requires:

lock
```

pyproject.toml dependencies:

```toml
[tool.poetry.dependencies]
python = "2.7.14"

beaker = "^1.9.0"
bottle = "^0.12.13"
funcsigs = "^1.0.2"
gevent = "^1.2.2"
greenlet = "^0.4.12"
influxdb = "^5.0.0"
jsoncomment = "^0.3.0"
netaddr = "^0.7.19"
numpy = "1.11.2"
pandas = "0.19.1"
pyrad = "~2.1"
python-dateutil = "^2.6.1"
pytz = "2017.2"
requests = "*"
schedule = "^0.4.2"
tacacs-plus = "~2.0"
ujson = "~1.35"
pymongo = "*"
h5py = "*"
environs = "*"
pyyaml = "*"
deprecated = "*"
appdirs = "*"
pycryptodome = "^3.4.11"
click = "*"
pyopenssl = "*"
pem = "*"
jinja2 = "*"
uwsgi = "*"
python-mimeparse = "*"
bcrypt = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.5"
rope = "*"
ipython = "^5.6.0"
mock = "*"
pylint = "*"
pylint-quotes = "^0.1.8"
yapf = "*"
teamcity-messages = "*"
webtest = "*"
requests-mock = "*"
pdbpp = "*"
pytest-mock = "*"
pytest-cov = "*"
pytest-pythonpath = "*"
pytest-pylint = "*"
```

**Comment by sdispater** [comment]
Could you execute the `lock` command in debug mode (`-vvv`) and post the results here?

**Comment by rainyday** [comment]
@sdispater in `0.10.0` it seems to just silently fail to install the package now. I'm not sure this is an improvement. If there's no way to respect the python version when deciding which version of a package to install (pipenv can't seem to do this either for what its worth), then some sort of notification would be preferable rather than stuff breaking without explanation.

**Comment by sdispater** [comment]
@rainyday What do you mean it fails to install the package? Which package?

**Comment by rainyday** [comment]
@sdispater sorry, forgot to set the python version in pyproject.toml. seems to work fine.
